name: simulated_annealing
description: Simulated annealing experiment in flutter applied to the traveling salesman problem.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true